#nacos注册中心配置
nacos:
  serverAddr: 10.7.31.13:28100
  namespace: public
  username: nacos
  password: nacos
  group: DEFAULT_GROUP
  dataId: report.yml

#本地服务信息配置
application:
  name: app-report
  port: 8080
  ip: 127.0.0.1
  group: DEFAULT_GROUP