DROP TABLE "DYNAMIC_REPORT";
CREATE TABLE "DYNAMIC_REPORT"
(
    "FORM_CODE" VARCHAR(30) NOT NULL,
    "FORM_NAME" VARCHAR(60) NOT NULL,
    "FORM_DEFAULT_CONTENT" CLOB NOT NULL,
    "FORM_DETAIL_CONTENT" CLOB,
    "VERSION" INT NOT NULL,
    "CREATOR" NUMERIC NOT NULL,
    "CREATE_TIME" TIMESTAMP(6) NOT NULL,
    "UPDATE_BY" NUMERIC,
    "UPDATE_TIME" TIMESTAMP(6),
        NOT                       CLUSTER PRIMARY KEY("FORM_CODE")
) STORAGE(ON "MAIN", CLUSTERBTR) ;


DROP TABLE "DYNAMIC_REPORT_HISTORY";
CREATE TABLE "DYNAMIC_REPORT_HISTORY"
(
"TEMPLATE_ID" VARCHAR(64) NOT NULL,
"FORM_CODE" VARCHAR(30) NOT NULL,
"FORM_DEFAULT_CONTENT" CLOB NOT NULL,
"FORM_DETAIL_CONTENT" CLOB,
"HISTORY_TIME" DATE NOT NULL,
"FORM_VERSION" NUMERIC NOT NULL,
"LAST_FLAG" VARCHAR(1) NOT NULL,
"VERSION" NUMERIC NOT NULL,
"CREATOR" NUMERIC NOT NULL,
"CREATE_TIME" TIMESTAMP(6) NOT NULL,
"UPDATE_BY" NUMERIC,
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("TEMPLATE_ID")
) STORAGE(ON "MAIN", CLUSTERBTR) ;