/*
 Navicat Premium Data Transfer

 Source Server         : 105oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 106.15.194.243:1521
 Source Schema         : HJ

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 20/12/2022 10:20:09
*/


-- ----------------------------
-- Table structure for DYNAMIC_REPORT
-- ----------------------------
DROP TABLE "DYNAMIC_REPORT";
CREATE TABLE "DYNAMIC_REPORT" (
  "FORM_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "FORM_NAME" VARCHAR2(60 BYTE) NOT NULL,
  "FORM_DEFAULT_CONTENT" CLOB NOT NULL,
  "FORM_DETAIL_CONTENT" CLOB,
  "VERSION" NUMBER NOT NULL,
  "CREATOR" NUMBER NOT NULL,
  "CREATE_TIME" DATE NOT NULL,
  "UPDATE_BY" NUMBER,
  "UPDATE_TIME" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Checks structure for table DYNAMIC_REPORT
-- ----------------------------
ALTER TABLE "DYNAMIC_REPORT" ADD CONSTRAINT "SYS_C0011303" CHECK ("FORM_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT" ADD CONSTRAINT "SYS_C0011304" CHECK ("FORM_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT" ADD CONSTRAINT "SYS_C0011305" CHECK ("FORM_DEFAULT_CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT" ADD CONSTRAINT "SYS_C0011306" CHECK ("VERSION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT" ADD CONSTRAINT "SYS_C0011307" CHECK ("CREATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT" ADD CONSTRAINT "SYS_C0011308" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;





/*
 Navicat Premium Data Transfer

 Source Server         : 105oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 106.15.194.243:1521
 Source Schema         : HJ

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 20/12/2022 10:20:30
*/


-- ----------------------------
-- Table structure for DYNAMIC_REPORT_HISTORY
-- ----------------------------
DROP TABLE "DYNAMIC_REPORT_HISTORY";
CREATE TABLE "DYNAMIC_REPORT_HISTORY" (
  "TEMPLATE_ID" VARCHAR2(64 BYTE) NOT NULL,
  "FORM_CODE" VARCHAR2(30 BYTE) NOT NULL,
  "FORM_DEFAULT_CONTENT" CLOB NOT NULL,
  "FORM_DETAIL_CONTENT" CLOB,
  "HISTORY_TIME" DATE NOT NULL,
  "FORM_VERSION" NUMBER NOT NULL,
  "LAST_FLAG" VARCHAR2(1 BYTE) NOT NULL,
  "VERSION" NUMBER NOT NULL,
  "CREATOR" NUMBER NOT NULL,
  "CREATE_TIME" DATE NOT NULL,
  "UPDATE_BY" NUMBER,
  "UPDATE_TIME" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Checks structure for table DYNAMIC_REPORT_HISTORY
-- ----------------------------
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011309" CHECK ("TEMPLATE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011310" CHECK ("FORM_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011311" CHECK ("FORM_DEFAULT_CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011312" CHECK ("HISTORY_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011313" CHECK ("FORM_VERSION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011314" CHECK ("LAST_FLAG" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011315" CHECK ("VERSION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011316" CHECK ("CREATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DYNAMIC_REPORT_HISTORY" ADD CONSTRAINT "SYS_C0011317" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
